### ISSUE TITLE
Google play store gives problem when downloading apps

### ISSUE THREAD

**Issue by TechEcoSafari** [AryanKedare/rel#3]
Hi Aryan Kedare,
I have tested your Pixel Experience ROM and I have this one issue. I am not able to download any app from google play store. It says download pending and it takes forver! Please look into this ASAP and please inform me how to fix it.

**Comment by jakues** [comment]
@TechEcoSafari Work for me

**Comment by TheHitMan7** [comment]
> Hi Aryan Kedare,
> I have tested your Pixel Experience ROM and I have this one issue. I am not able to download any app from google play store. It says download pending and it takes forver! Please look into this ASAP and please inform me how to fix it.

He can do  nothing on this. Better you update your Playstore. I happens here many times but after an update. It will be fine.
